### ISSUE TITLE
pipeline fails

### ISSUE THREAD

**Issue by fxbrit** [luco5826/group03-user-registration#15]
according to the output `contextLoads() FAILED`, which is the same output I get when running the tests locally without first running the postgres container. should we port all the tests to disposable containers or should we just add a step to [workflows/run-tests.yml](https://github.com/luco5826/group03-user-registration/blob/master/.github/workflows/run-tests.yml)?

**Comment by luco5826** [comment]
I think we should port all the tests to disposable containers, since the CI/CD pipeline could be already running in a docker container we cannot spawn another container just for postgres

**Comment by fxbrit** [comment]
agreed, I will include it in #10
