### ISSUE TITLE
Unit tests for extension functions (`toDTO` functions)

### ISSUE THREAD

**Issue by fxbrit** [luco5826/group03-user-registration#6]

**Comment by fxbrit** [comment]
ops clicked by mistake.

**Comment by fxbrit** [comment]
@luco5826 when you wrote the roadmap did you have anything specific in mind? other than testing that the DTO is actually created with the passed value I can't really imagine many tests.

maybe I should test empty strings in the name and email fields?

**Comment by luco5826** [comment]
@fxbrit Nope, didn't think of any test, just copied what was written in the PDF
![image](https://user-images.githubusercontent.com/38291180/162577537-18d23455-95bd-40c2-b701-f1a94be4e3eb.png)

**Comment by fxbrit** [comment]
k, I pushed the ones for the UserDTO with everything I could think of.

**Comment by luco5826** [comment]
I'm sure our PRs will conflict since I've renamed the `toUserDTO()` into `toDTO()` as suggested in the lab, anyway we will have to fix it

**Comment by fxbrit** [comment]
how dare you..

**Comment by luco5826** [comment]
Well, since your PR is still a draft.....
